export const INVOICE_LIST_REQUEST = 'INVOICE_LIST_REQUEST'
export const INVOICE_LIST_SUCCESS = 'INVOICE_LIST_SUCCESS'
export const INVOICE_LIST_FAIL = 'INVOICE_LIST_FAIL'

export const SET_NEXT_INVOICE_NUMBER = 'SET_NEXT_INVOICE_NUMBER'

export const INVOICE_DETAILS_REQUEST = 'INVOICE_DETAILS_REQUEST'
export const INVOICE_DETAILS_SUCCESS = 'INVOICE_DETAILS_SUCCESS'
export const INVOICE_DETAILS_FAIL = 'INVOICE_DETAILS_FAIL'

export const INVOICE_CREATE_REQUEST = 'INVOICE_CREATE_REQUEST'
export const INVOICE_CREATE_SUCCESS = 'INVOICE_CREATE_SUCCESS'
export const INVOICE_CREATE_FAIL = 'INVOICE_CREATE_FAIL'
export const INVOICE_MODAL_SHOW = 'INVOICE_MODAL_SHOW'
export const INVOICE_MODAL_HIDE = 'INVOICE_MODAL_HIDE'

export const SET_CURRENT_INVOICE = 'SET_CURRENT_INVOICE'
export const INVOICE_UPDATE_REQUEST = 'INVOICE_UPDATE_REQUEST'
export const INVOICE_UPDATE_SUCCESS = 'INVOICE_UPDATE_SUCCESS'
export const INVOICE_UPDATE_FAIL = 'INVOICE_UPDATE_FAIL'

export const INVOICE_DELETE_REQUEST = 'INVOICE_DELETE_REQUEST'
export const INVOICE_DELETE_SUCCESS = 'INVOICE_DELETE_SUCCESS'
export const INVOICE_DELETE_FAIL = 'INVOICE_DELETE_FAIL'

export const SET_AVR_DATE_MODAL_ON = 'SET_AVR_DATE_MODAL_ON'
export const SET_AVR_DATE_MODAL_OFF = 'SET_AVR_DATE_MODAL_OFF'
export const SET_AVR_DATE = 'SET_AVR_DATE'
